apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: simian-human-clean-architecture
spec:
  selector:
    matchLabels:
      app: simian-human
  replicas: 4
  template:
    metadata:
      labels:
        app: simian-human
    spec:
      containers:
      - name: simian-human
        image: brunooliveiramac/mercado-livre
        ports:
        - containerPort: 8080
          name: server
