apiVersion: v1
kind: Service
metadata:
  name: simian-human-clean-architecture
  labels:
    app: simian-human
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: simian-human
  type: NodePort
