CREATE SCHEMA IF NOT EXISTS CLEAN_ARCHITECTURE;

SET SCHEMA CLEAN_ARCHITECTURE;

CREATE TABLE CLEAN_ARCHITECTURE.DNA (
    ID            NUMBER          NOT NULL,
    DNA_SEQUENCE          VARCHAR2(255)    NOT NULL UNIQUE,
    DNA_TYPE          VARCHAR2(255)   NOT NULL,
    CREATED_DATE  DATE
);

ALTER TABLE CLEAN_ARCHITECTURE.DNA ADD CONSTRAINT DNA_PK PRIMARY KEY (ID);

CREATE SEQUENCE CLEAN_ARCHITECTURE.DNA_ID_SEQ MINVALUE 1 NOMAXVALUE INCREMENT BY 1 START WITH 1 CACHE 10 NOCYCLE;

